# Dockerfile-payment

FROM node:20.13.1-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the application
COPY . ./

# Expose port 3001
EXPOSE 3001

CMD ["node", "app.js"]
