version: '3.8'

services:
  account-manager:
    build:
      context: ./account            # Set the context to the account directory
      dockerfile: Dockerfile-account
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file:
      - .env

  payment-manager:
    build:
      context: ./payment            # Set the context to the payment directory
      dockerfile: Dockerfile-payment
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo 
    restart: unless-stopped
