# Dockerfile-account

# Use official Node.js image as base
FROM node:20.13.1-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the application
COPY . ./

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD ["node", "app.js"]
